import type { GallerySectionData } from "./galleryTypes";

export const galleryLegacySections: GallerySectionData[] = [
  {
    id: "guests",
    title: "Our Happy Guests",
    subtitle: "Moments shared by our guests at the lodge.",
    images: [
      {
        src: "/images/client_experiences/relaxing/IMG_2649.webp",
        alt: "Client enjoying the lodge",
        width: 1920,
        height: 1080,
        blurDataURL: "",
      },
      {
        src: "/images/client_experiences/relaxing/IMG_2650.webp",
        alt: "Client relaxing in the garden",
        width: 1920,
        height: 1080,
        blurDataURL: "",
      },
      {
        src: "/images/client_experiences/relaxing/IMG_2656.webp",
        alt: "Guests enjoying dinner",
        width: 1920,
        height: 1080,
        blurDataURL: "",
      },
    ],
  },
  {
    id: "check-in",
    title: "Arrival Moments",
    subtitle: "Welcoming our guests at reception.",
    images: [
      {
        src: "/images/client_experiences/checking_in/20240701_175712.webp",
        alt: "Clients checking in at the lodge",
        width: 1920,
        height: 1080,
        blurDataURL: "",
      },
      {
        src: "/images/client_experiences/checking_in/20240701_175747.webp",
        alt: "Clients at the reception",
        width: 1920,
        height: 1080,
        blurDataURL: "",
      },
      {
        src: "/images/client_experiences/checking_in/20240701_175717.webp",
        alt: "Clients enjoying welcome drinks",
        width: 1920,
        height: 1080,
        blurDataURL: "",
      },
    ],
  },
  {
    id: "wildlife",
    title: "Rwanda Wildlife",
    subtitle: "Close encounters with Rwanda's remarkable wildlife.",
    images: [
      {
        src: "/images/wildlife/buffalo-group-image.jpeg",
        alt: "A group of African buffalo resting and standing alert in dry bushland.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/african-fish-eagle-image.jpeg",
        alt: "An African Fish Eagle perched on a tree branch by the water, with smaller birds nearby.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/buffalo-trio-image.jpeg",
        alt: "Three African buffalo in the savanna, one lying down and two standing watchfully.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/warthogs-grazing-image.jpeg",
        alt: "Two warthogs grazing on dry grass near a lakeshore.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/hippos-in-river-image.jpeg",
        alt: "A group of hippos partially submerged in water, with eyes and ears visible above the surface.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/buffalo-pair-image.jpeg",
        alt: "Two African buffalo resting in dry grass with dense bush in the background.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/warthogs-by-water-image.jpeg",
        alt: "A pair of warthogs walking and grazing near tall grass by the water.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/warthogs-closeup-image.jpeg",
        alt: "Close-up of two warthogs grazing, showing their tusks and rough coats.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/warthogs-sidewalk-image.jpeg",
        alt: "Two warthogs walking side by side across dry grassland with a lake in the distance.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/gorilla-family-image.jpeg",
        alt: "A large silverback gorilla sitting beside a younger gorilla in dense green forest vegetation.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/rhino-grassland-image.jpeg",
        alt: "A rhinoceros partially hidden in tall dry grass with scattered trees in the savanna.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/zebra-mother-calf-image.jpeg",
        alt: "A zebra with its young calf grazing beside a tree in golden grassland.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/giraffe-silhouette-image.jpeg",
        alt: "A tall giraffe standing against a hazy sky, surrounded by sparse trees.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/baboons-roadside-image.jpeg",
        alt: "A troop of baboons gathered on a dirt road, grooming and interacting with each other.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/zebra-closeup-image.jpeg",
        alt: "Close-up view of a zebra's black-and-white striped pattern with its mane standing upright.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/gorillas-resting-image.jpeg",
        alt: "Two gorillas lying down and resting amidst dense green vegetation.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/rhino-pair-image.jpeg",
        alt: "Two rhinoceroses grazing among dry bushes and grass in the savanna.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/zebras-grazing-image.jpeg",
        alt: "A zebra and its calf feeding near trees, with another zebra grazing in the background.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/gorilla-duo-image.jpeg",
        alt: "Two gorillas sitting closely together in lush greenery, one facing the other thoughtfully.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/zebra-herd-image.jpeg",
        alt: "A small group of zebras in tall grass, with a mother and calf standing side by side.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/hippos-riverbank-image.jpeg",
        alt: "A group of hippos with only their heads visible above the water near tall riverbank grass.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/giraffe-sunset-image.jpeg",
        alt: "A giraffe standing tall against a hazy sunset sky with surrounding trees and bushes.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/baboon-mother-infant-image.jpeg",
        alt: "A baboon sitting on the ground holding an infant close to her chest.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/baboons-duo-image.jpeg",
        alt: "Two baboons in the savanna, one facing forward and one with its back turned.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
      {
        src: "/images/wildlife/elephant-riverbank-image.jpeg",
        alt: "An elephant seen from behind, feeding on thick greenery along the river's edge.",
        width: 1600,
        height: 1067,
        blurDataURL: "",
      },
    ],
  },
];
