export type GalleryImage = {
  src: string;
  alt: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export type GallerySectionData = {
  id: string;
  title: string;
  subtitle: string;
  images: GalleryImage[];
};

export const gallerySections: GallerySectionData[] = [
  {
    id: 'lodge',
    title: 'Lodge & Grounds',
    subtitle: 'Explore the exterior, lobby, bamboo garden, and grounds.',
    images: [
      {
        src: '/images/gallery/lodge/exterior/lebambou-exterior-001.webp',
        alt: 'Lodge exterior 1',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/exterior/lebambou-exterior-002.webp',
        alt: 'Lodge exterior 2',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/exterior/lebambou-exterior-003.webp',
        alt: 'Lodge exterior 3',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/grounds/lebambou-grounds-001.webp',
        alt: 'Lodge grounds 1',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/grounds/lebambou-grounds-002.webp',
        alt: 'Lodge grounds 2',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/grounds/lebambou-grounds-003.webp',
        alt: 'Lodge grounds 3',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/grounds/lebambou-grounds-004.webp',
        alt: 'Lodge grounds 4',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/grounds/lebambou-grounds-005.webp',
        alt: 'Lodge grounds 5',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/grounds/lebambou-grounds-006.webp',
        alt: 'Lodge grounds 6',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/grounds/lebambou-grounds-007.webp',
        alt: 'Lodge grounds 7',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/grounds/lebambou-grounds-008.webp',
        alt: 'Lodge grounds 8',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/grounds/lebambou-grounds-009.webp',
        alt: 'Lodge grounds 9',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/grounds/lebambou-grounds-010.webp',
        alt: 'Lodge grounds 10',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/grounds/lebambou-grounds-011.webp',
        alt: 'Lodge grounds 11',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/grounds/lebambou-grounds-012.webp',
        alt: 'Lodge grounds 12',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/bamboo-garden/lebambou-bamboogarden-001.webp',
        alt: 'Bamboo garden 1',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/bamboo-garden/lebambou-bamboogarden-002.webp',
        alt: 'Bamboo garden 2',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/bamboo-garden/lebambou-bamboogarden-003.webp',
        alt: 'Bamboo garden 3',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/bamboo-garden/lebambou-bamboogarden-004.webp',
        alt: 'Bamboo garden 4',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/bamboo-garden/lebambou-bamboogarden-005.webp',
        alt: 'Bamboo garden 5',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/bamboo-garden/lebambou-bamboogarden-006.webp',
        alt: 'Bamboo garden 6',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/bamboo-garden/lebambou-bamboogarden-007.webp',
        alt: 'Bamboo garden 7',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/bamboo-garden/lebambou-bamboogarden-008.webp',
        alt: 'Bamboo garden 8',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-001.webp',
        alt: 'Lobby and lounge 1',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-002.webp',
        alt: 'Lobby and lounge 2',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-003.webp',
        alt: 'Lobby and lounge 3',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-004.webp',
        alt: 'Lobby and lounge 4',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-005.webp',
        alt: 'Lobby and lounge 5',
        width: 2600,
        height: 1951,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-006.webp',
        alt: 'Lobby and lounge 6',
        width: 1951,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-007.webp',
        alt: 'Lobby and lounge 7',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-008.webp',
        alt: 'Lobby and lounge 8',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-009.webp',
        alt: 'Lobby and lounge 9',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-010.webp',
        alt: 'Lobby and lounge 10',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-011.webp',
        alt: 'Lobby and lounge 11',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-012.webp',
        alt: 'Lobby and lounge 12',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-013.webp',
        alt: 'Lobby and lounge 13',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-014.webp',
        alt: 'Lobby and lounge 14',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-015.webp',
        alt: 'Lobby and lounge 15',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-016.webp',
        alt: 'Lobby and lounge 16',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-017.webp',
        alt: 'Lobby and lounge 17',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-018.webp',
        alt: 'Lobby and lounge 18',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-019.webp',
        alt: 'Lobby and lounge 19',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-020.webp',
        alt: 'Lobby and lounge 20',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-021.webp',
        alt: 'Lobby and lounge 21',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-022.webp',
        alt: 'Lobby and lounge 22',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-023.webp',
        alt: 'Lobby and lounge 23',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-024.webp',
        alt: 'Lobby and lounge 24',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-025.webp',
        alt: 'Lobby and lounge 25',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-026.webp',
        alt: 'Lobby and lounge 26',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-027.webp',
        alt: 'Lobby and lounge 27',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-028.webp',
        alt: 'Lobby and lounge 28',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-029.webp',
        alt: 'Lobby and lounge 29',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-030.webp',
        alt: 'Lobby and lounge 30',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-031.webp',
        alt: 'Lobby and lounge 31',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-032.webp',
        alt: 'Lobby and lounge 32',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-033.webp',
        alt: 'Lobby and lounge 33',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-034.webp',
        alt: 'Lobby and lounge 34',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-035.webp',
        alt: 'Lobby and lounge 35',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-036.webp',
        alt: 'Lobby and lounge 36',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-037.webp',
        alt: 'Lobby and lounge 37',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-038.webp',
        alt: 'Lobby and lounge 38',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-039.webp',
        alt: 'Lobby and lounge 39',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-040.webp',
        alt: 'Lobby and lounge 40',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/lodge/lobby/lebambou-lobby-041.webp',
        alt: 'Lobby and lounge 41',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
    ],
  },
  {
    id: 'rooms',
    title: 'Rooms & Suites',
    subtitle: 'Comfortable rooms for every kind of stay.',
    images: [
      {
        src: '/images/gallery/rooms/single/lebambou-singleroom-001.webp',
        alt: 'Single room 1',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/single/lebambou-singleroom-002.webp',
        alt: 'Single room 2',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/single/lebambou-singleroom-003.webp',
        alt: 'Single room 3',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/single/lebambou-singleroom-004.webp',
        alt: 'Single room 4',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/single/lebambou-singleroom-005.webp',
        alt: 'Single room 5',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/single/lebambou-singleroom-006.webp',
        alt: 'Single room 6',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-001.webp',
        alt: 'Double room 1',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-002.webp',
        alt: 'Double room 2',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-003.webp',
        alt: 'Double room 3',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-004.webp',
        alt: 'Double room 4',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-005.webp',
        alt: 'Double room 5',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-006.webp',
        alt: 'Double room 6',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-007.webp',
        alt: 'Double room 7',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-008.webp',
        alt: 'Double room 8',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-009.webp',
        alt: 'Double room 9',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-010.webp',
        alt: 'Double room 10',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-011.webp',
        alt: 'Double room 11',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-012.webp',
        alt: 'Double room 12',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-013.webp',
        alt: 'Double room 13',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-014.webp',
        alt: 'Double room 14',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-015.webp',
        alt: 'Double room 15',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-016.webp',
        alt: 'Double room 16',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-017.webp',
        alt: 'Double room 17',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-018.webp',
        alt: 'Double room 18',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-019.webp',
        alt: 'Double room 19',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-020.webp',
        alt: 'Double room 20',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-021.webp',
        alt: 'Double room 21',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-022.webp',
        alt: 'Double room 22',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-023.webp',
        alt: 'Double room 23',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-024.webp',
        alt: 'Double room 24',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-025.webp',
        alt: 'Double room 25',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-026.webp',
        alt: 'Double room 26',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-027.webp',
        alt: 'Double room 27',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-028.webp',
        alt: 'Double room 28',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-029.webp',
        alt: 'Double room 29',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-030.webp',
        alt: 'Double room 30',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-031.webp',
        alt: 'Double room 31',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-032.webp',
        alt: 'Double room 32',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-033.webp',
        alt: 'Double room 33',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-034.webp',
        alt: 'Double room 34',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-035.webp',
        alt: 'Double room 35',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-036.webp',
        alt: 'Double room 36',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-037.webp',
        alt: 'Double room 37',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-038.webp',
        alt: 'Double room 38',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-039.webp',
        alt: 'Double room 39',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-040.webp',
        alt: 'Double room 40',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-041.webp',
        alt: 'Double room 41',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-042.webp',
        alt: 'Double room 42',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-043.webp',
        alt: 'Double room 43',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-044.webp',
        alt: 'Double room 44',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-045.webp',
        alt: 'Double room 45',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-046.webp',
        alt: 'Double room 46',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-047.webp',
        alt: 'Double room 47',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-048.webp',
        alt: 'Double room 48',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-049.webp',
        alt: 'Double room 49',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-050.webp',
        alt: 'Double room 50',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-051.webp',
        alt: 'Double room 51',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/double/lebambou-doubleroom-052.webp',
        alt: 'Double room 52',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-001.webp',
        alt: 'Twin room 1',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-002.webp',
        alt: 'Twin room 2',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-003.webp',
        alt: 'Twin room 3',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-004.webp',
        alt: 'Twin room 4',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-005.webp',
        alt: 'Twin room 5',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-006.webp',
        alt: 'Twin room 6',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-007.webp',
        alt: 'Twin room 7',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-008.webp',
        alt: 'Twin room 8',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-009.webp',
        alt: 'Twin room 9',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-010.webp',
        alt: 'Twin room 10',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-011.webp',
        alt: 'Twin room 11',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-012.webp',
        alt: 'Twin room 12',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-013.webp',
        alt: 'Twin room 13',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-014.webp',
        alt: 'Twin room 14',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-015.webp',
        alt: 'Twin room 15',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-016.webp',
        alt: 'Twin room 16',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-017.webp',
        alt: 'Twin room 17',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-018.webp',
        alt: 'Twin room 18',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-019.webp',
        alt: 'Twin room 19',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-020.webp',
        alt: 'Twin room 20',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-021.webp',
        alt: 'Twin room 21',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-022.webp',
        alt: 'Twin room 22',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-023.webp',
        alt: 'Twin room 23',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-024.webp',
        alt: 'Twin room 24',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-025.webp',
        alt: 'Twin room 25',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-026.webp',
        alt: 'Twin room 26',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-027.webp',
        alt: 'Twin room 27',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-028.webp',
        alt: 'Twin room 28',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-029.webp',
        alt: 'Twin room 29',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-030.webp',
        alt: 'Twin room 30',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-031.webp',
        alt: 'Twin room 31',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-032.webp',
        alt: 'Twin room 32',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-033.webp',
        alt: 'Twin room 33',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/twin/lebambou-twinroom-034.webp',
        alt: 'Twin room 34',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/triple/lebambou-tripleroom-001.webp',
        alt: 'Triple room 1',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/triple/lebambou-tripleroom-002.webp',
        alt: 'Triple room 2',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/triple/lebambou-tripleroom-003.webp',
        alt: 'Triple room 3',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/triple/lebambou-tripleroom-004.webp',
        alt: 'Triple room 4',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/triple/lebambou-tripleroom-005.webp',
        alt: 'Triple room 5',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/triple/lebambou-tripleroom-006.webp',
        alt: 'Triple room 6',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/triple/lebambou-tripleroom-007.webp',
        alt: 'Triple room 7',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/triple/lebambou-tripleroom-008.webp',
        alt: 'Triple room 8',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/triple/lebambou-tripleroom-009.webp',
        alt: 'Triple room 9',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/triple/lebambou-tripleroom-010.webp',
        alt: 'Triple room 10',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/triple/lebambou-tripleroom-011.webp',
        alt: 'Triple room 11',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/triple/lebambou-tripleroom-012.webp',
        alt: 'Triple room 12',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/triple/lebambou-tripleroom-013.webp',
        alt: 'Triple room 13',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/triple/lebambou-tripleroom-014.webp',
        alt: 'Triple room 14',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/triple/lebambou-tripleroom-015.webp',
        alt: 'Triple room 15',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/triple/lebambou-tripleroom-017.webp',
        alt: 'Triple room 16',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/triple/lebambou-tripleroom-018.webp',
        alt: 'Triple room 17',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/triple/lebambou-tripleroom-019.webp',
        alt: 'Triple room 18',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/family-cottage/lebambou-familycottage-001.webp',
        alt: 'Family cottage 1',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/family-cottage/lebambou-familycottage-002.webp',
        alt: 'Family cottage 2',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/family-cottage/lebambou-familycottage-003.webp',
        alt: 'Family cottage 3',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/family-cottage/lebambou-familycottage-004.webp',
        alt: 'Family cottage 4',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/family-cottage/lebambou-familycottage-005.webp',
        alt: 'Family cottage 5',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/family-cottage/lebambou-familycottage-006.webp',
        alt: 'Family cottage 6',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/family-cottage/lebambou-familycottage-007.webp',
        alt: 'Family cottage 7',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/family-cottage/lebambou-familycottage-008.webp',
        alt: 'Family cottage 8',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/family-cottage/lebambou-familycottage-009.webp',
        alt: 'Family cottage 9',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/family-cottage/lebambou-familycottage-010.webp',
        alt: 'Family cottage 10',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/family-cottage/lebambou-familycottage-011.webp',
        alt: 'Family cottage 11',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/family-cottage/lebambou-familycottage-012.webp',
        alt: 'Family cottage 12',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/family-cottage/lebambou-familycottage-013.webp',
        alt: 'Family cottage 13',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/family-cottage/lebambou-familycottage-014.webp',
        alt: 'Family cottage 14',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/family-cottage/lebambou-familycottage-015.webp',
        alt: 'Family cottage 15',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/family-cottage/lebambou-familycottage-016.webp',
        alt: 'Family cottage 16',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/family-cottage/lebambou-familycottage-017.webp',
        alt: 'Family cottage 17',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/rooms/family-cottage/lebambou-familycottage-018.webp',
        alt: 'Family cottage 18',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
    ],
  },
  {
    id: 'dining',
    title: 'Dining & Cuisine',
    subtitle: 'A taste of Le Bambou, from restaurant to table.',
    images: [
      {
        src: '/images/gallery/dining/restaurant/lebambou-restaurant-001.webp',
        alt: 'Restaurant and dining 1',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/dining/restaurant/lebambou-restaurant-002.webp',
        alt: 'Restaurant and dining 2',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/dining/restaurant/lebambou-restaurant-003.webp',
        alt: 'Restaurant and dining 3',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/dining/restaurant/lebambou-restaurant-004.webp',
        alt: 'Restaurant and dining 4',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/dining/restaurant/lebambou-restaurant-005.webp',
        alt: 'Restaurant and dining 5',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/dining/food/lebambou-food-001.webp',
        alt: 'Le Bambou cuisine 1',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/dining/food/lebambou-food-002.webp',
        alt: 'Le Bambou cuisine 2',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/dining/food/lebambou-food-003.webp',
        alt: 'Le Bambou cuisine 3',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/dining/food/lebambou-food-004.webp',
        alt: 'Le Bambou cuisine 4',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/dining/food/lebambou-food-005.webp',
        alt: 'Le Bambou cuisine 5',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/dining/food/lebambou-food-006.webp',
        alt: 'Le Bambou cuisine 6',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/dining/food/lebambou-food-007.webp',
        alt: 'Le Bambou cuisine 7',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/dining/food/lebambou-food-008.webp',
        alt: 'Le Bambou cuisine 8',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/dining/food/lebambou-food-009.webp',
        alt: 'Le Bambou cuisine 9',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/dining/food/lebambou-food-010.webp',
        alt: 'Le Bambou cuisine 10',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/dining/food/lebambou-food-011.webp',
        alt: 'Le Bambou cuisine 11',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/dining/food/lebambou-food-012.webp',
        alt: 'Le Bambou cuisine 12',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/dining/food/lebambou-food-013.webp',
        alt: 'Le Bambou cuisine 13',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/dining/food/lebambou-food-014.webp',
        alt: 'Le Bambou cuisine 14',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/dining/food/lebambou-food-015.webp',
        alt: 'Le Bambou cuisine 15',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/dining/food/lebambou-food-016.webp',
        alt: 'Le Bambou cuisine 16',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
    ],
  },
  {
    id: 'attractions',
    title: 'Attractions & Culture',
    subtitle: 'Discover the Ellen campus and Gorilla Guardians Village.',
    images: [
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-001.webp',
        alt: 'Ellen DeGeneres Campus 1',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-002.webp',
        alt: 'Ellen DeGeneres Campus 2',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-003.webp',
        alt: 'Ellen DeGeneres Campus 3',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-004.webp',
        alt: 'Ellen DeGeneres Campus 4',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-005.webp',
        alt: 'Ellen DeGeneres Campus 5',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-006.webp',
        alt: 'Ellen DeGeneres Campus 6',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-007.webp',
        alt: 'Ellen DeGeneres Campus 7',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-008.webp',
        alt: 'Ellen DeGeneres Campus 8',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-009.webp',
        alt: 'Ellen DeGeneres Campus 9',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-010.webp',
        alt: 'Ellen DeGeneres Campus 10',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-011.webp',
        alt: 'Ellen DeGeneres Campus 11',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-012.webp',
        alt: 'Ellen DeGeneres Campus 12',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-013.webp',
        alt: 'Ellen DeGeneres Campus 13',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-014.webp',
        alt: 'Ellen DeGeneres Campus 14',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-015.webp',
        alt: 'Ellen DeGeneres Campus 15',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-016.webp',
        alt: 'Ellen DeGeneres Campus 16',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-017.webp',
        alt: 'Ellen DeGeneres Campus 17',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-018.webp',
        alt: 'Ellen DeGeneres Campus 18',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-019.webp',
        alt: 'Ellen DeGeneres Campus 19',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-020.webp',
        alt: 'Ellen DeGeneres Campus 20',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-021.webp',
        alt: 'Ellen DeGeneres Campus 21',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-022.webp',
        alt: 'Ellen DeGeneres Campus 22',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-023.webp',
        alt: 'Ellen DeGeneres Campus 23',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-024.webp',
        alt: 'Ellen DeGeneres Campus 24',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-025.webp',
        alt: 'Ellen DeGeneres Campus 25',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/ellen-campus/ellendegenerescampus-026.webp',
        alt: 'Ellen DeGeneres Campus 26',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-001.webp',
        alt: 'Gorilla Guardians cultural performance 1',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-002.webp',
        alt: 'Gorilla Guardians cultural performance 2',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-003.webp',
        alt: 'Gorilla Guardians cultural performance 3',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-004.webp',
        alt: 'Gorilla Guardians cultural performance 4',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-005.webp',
        alt: 'Gorilla Guardians cultural performance 5',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-006.webp',
        alt: 'Gorilla Guardians cultural performance 6',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-007.webp',
        alt: 'Gorilla Guardians cultural performance 7',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-008.webp',
        alt: 'Gorilla Guardians cultural performance 8',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-009.webp',
        alt: 'Gorilla Guardians cultural performance 9',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-010.webp',
        alt: 'Gorilla Guardians cultural performance 10',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-011.webp',
        alt: 'Gorilla Guardians cultural performance 11',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-012.webp',
        alt: 'Gorilla Guardians cultural performance 12',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-013.webp',
        alt: 'Gorilla Guardians cultural performance 13',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-014.webp',
        alt: 'Gorilla Guardians cultural performance 14',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-015.webp',
        alt: 'Gorilla Guardians cultural performance 15',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-016.webp',
        alt: 'Gorilla Guardians cultural performance 16',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-017.webp',
        alt: 'Gorilla Guardians cultural performance 17',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-018.webp',
        alt: 'Gorilla Guardians cultural performance 18',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-019.webp',
        alt: 'Gorilla Guardians cultural performance 19',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-020.webp',
        alt: 'Gorilla Guardians cultural performance 20',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-021.webp',
        alt: 'Gorilla Guardians cultural performance 21',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-022.webp',
        alt: 'Gorilla Guardians cultural performance 22',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-023.webp',
        alt: 'Gorilla Guardians cultural performance 23',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-024.webp',
        alt: 'Gorilla Guardians cultural performance 24',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-025.webp',
        alt: 'Gorilla Guardians cultural performance 25',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-026.webp',
        alt: 'Gorilla Guardians cultural performance 26',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-027.webp',
        alt: 'Gorilla Guardians cultural performance 27',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-028.webp',
        alt: 'Gorilla Guardians cultural performance 28',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-029.webp',
        alt: 'Gorilla Guardians cultural performance 29',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-030.webp',
        alt: 'Gorilla Guardians cultural performance 30',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-031.webp',
        alt: 'Gorilla Guardians cultural performance 31',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-032.webp',
        alt: 'Gorilla Guardians cultural performance 32',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-033.webp',
        alt: 'Gorilla Guardians cultural performance 33',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-034.webp',
        alt: 'Gorilla Guardians cultural performance 34',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-035.webp',
        alt: 'Gorilla Guardians cultural performance 35',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-036.webp',
        alt: 'Gorilla Guardians cultural performance 36',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-037.webp',
        alt: 'Gorilla Guardians cultural performance 37',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-038.webp',
        alt: 'Gorilla Guardians cultural performance 38',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-039.webp',
        alt: 'Gorilla Guardians cultural performance 39',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-040.webp',
        alt: 'Gorilla Guardians cultural performance 40',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-041.webp',
        alt: 'Gorilla Guardians cultural performance 41',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-042.webp',
        alt: 'Gorilla Guardians cultural performance 42',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-043.webp',
        alt: 'Gorilla Guardians cultural performance 43',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-044.webp',
        alt: 'Gorilla Guardians cultural performance 44',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-045.webp',
        alt: 'Gorilla Guardians cultural performance 45',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-046.webp',
        alt: 'Gorilla Guardians cultural performance 46',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-047.webp',
        alt: 'Gorilla Guardians cultural performance 47',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-048.webp',
        alt: 'Gorilla Guardians cultural performance 48',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-049.webp',
        alt: 'Gorilla Guardians cultural performance 49',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-050.webp',
        alt: 'Gorilla Guardians cultural performance 50',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-051.webp',
        alt: 'Gorilla Guardians cultural performance 51',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-052.webp',
        alt: 'Gorilla Guardians cultural performance 52',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-053.webp',
        alt: 'Gorilla Guardians cultural performance 53',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-054.webp',
        alt: 'Gorilla Guardians cultural performance 54',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-055.webp',
        alt: 'Gorilla Guardians cultural performance 55',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/cultural/gorillaguardiansvillage-culturalperformance-056.webp',
        alt: 'Gorilla Guardians cultural performance 56',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/drumming/gorillaguardiansvillage-drumming-001.webp',
        alt: 'Gorilla Guardians drumming 1',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/drumming/gorillaguardiansvillage-drumming-002.webp',
        alt: 'Gorilla Guardians drumming 2',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/drumming/gorillaguardiansvillage-drumming-003.webp',
        alt: 'Gorilla Guardians drumming 3',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/drumming/gorillaguardiansvillage-drumming-004.webp',
        alt: 'Gorilla Guardians drumming 4',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/attractions/gorilla-guardians/drumming/gorillaguardiansvillage-drumming-005.webp',
        alt: 'Gorilla Guardians drumming 5',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
    ],
  },
  {
    id: 'road-journey',
    title: 'Road Journey',
    subtitle: 'Scenes from the drive to Le Bambou.',
    images: [
      {
        src: '/images/gallery/road-journey/roadtolebambou-scenery-001.webp',
        alt: 'Road journey scenery 1',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/road-journey/roadtolebambou-scenery-002.webp',
        alt: 'Road journey scenery 2',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/road-journey/roadtolebambou-scenery-003.webp',
        alt: 'Road journey scenery 3',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/road-journey/roadtolebambou-scenery-004.webp',
        alt: 'Road journey scenery 4',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/road-journey/roadtolebambou-scenery-005.webp',
        alt: 'Road journey scenery 5',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/road-journey/roadtolebambou-scenery-006.webp',
        alt: 'Road journey scenery 6',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/road-journey/roadtolebambou-scenery-007.webp',
        alt: 'Road journey scenery 7',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/road-journey/roadtolebambou-scenery-008.webp',
        alt: 'Road journey scenery 8',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/road-journey/roadtolebambou-scenery-009.webp',
        alt: 'Road journey scenery 9',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/road-journey/roadtolebambou-scenery-010.webp',
        alt: 'Road journey scenery 10',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/road-journey/roadtolebambou-scenery-011.webp',
        alt: 'Road journey scenery 11',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/road-journey/roadtolebambou-scenery-012.webp',
        alt: 'Road journey scenery 12',
        width: 2600,
        height: 1950,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/road-journey/roadtolebambou-scenery-013.webp',
        alt: 'Road journey scenery 13',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
      {
        src: '/images/gallery/road-journey/roadtolebambou-scenery-014.webp',
        alt: 'Road journey scenery 14',
        width: 1950,
        height: 2600,
        blurDataURL: '',
      },
    ],
  },
  {
    id: 'guests',
    title: 'Our Happy Guests',
    subtitle: 'Moments shared by our guests at the lodge.',
    images: [
      {
        src: '/images/client_experiences/relaxing/IMG_2649.webp',
        alt: 'Client enjoying the lodge',
        width: 1920,
        height: 1080,
        blurDataURL: '',
      },
      {
        src: '/images/client_experiences/relaxing/IMG_2650.webp',
        alt: 'Client relaxing in the garden',
        width: 1920,
        height: 1080,
        blurDataURL: '',
      },
      {
        src: '/images/client_experiences/relaxing/IMG_2656.webp',
        alt: 'Guests enjoying dinner',
        width: 1920,
        height: 1080,
        blurDataURL: '',
      },
    ],
  },
  {
    id: 'check-in',
    title: 'Arrival Moments',
    subtitle: 'Welcoming our guests at reception.',
    images: [
      {
        src: '/images/client_experiences/checking_in/20240701_175712.webp',
        alt: 'Clients checking in at the lodge',
        width: 1920,
        height: 1080,
        blurDataURL: '',
      },
      {
        src: '/images/client_experiences/checking_in/20240701_175747.webp',
        alt: 'Clients at the reception',
        width: 1920,
        height: 1080,
        blurDataURL: '',
      },
      {
        src: '/images/client_experiences/checking_in/20240701_175717.webp',
        alt: 'Clients enjoying welcome drinks',
        width: 1920,
        height: 1080,
        blurDataURL: '',
      },
    ],
  },
  {
    id: 'wildlife',
    title: 'Rwanda Wildlife',
    subtitle: 'Close encounters with Rwanda\'s remarkable wildlife.',
    images: [
      {
        src: '/images/wildlife/buffalo-group-image.jpeg',
        alt: 'A group of African buffalo resting and standing alert in dry bushland.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/african-fish-eagle-image.jpeg',
        alt: 'An African Fish Eagle perched on a tree branch by the water, with smaller birds nearby.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/buffalo-trio-image.jpeg',
        alt: 'Three African buffalo in the savanna, one lying down and two standing watchfully.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/warthogs-grazing-image.jpeg',
        alt: 'Two warthogs grazing on dry grass near a lakeshore.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/hippos-in-river-image.jpeg',
        alt: 'A group of hippos partially submerged in water, with eyes and ears visible above the surface.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/buffalo-pair-image.jpeg',
        alt: 'Two African buffalo resting in dry grass with dense bush in the background.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/warthogs-by-water-image.jpeg',
        alt: 'A pair of warthogs walking and grazing near tall grass by the water.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/warthogs-closeup-image.jpeg',
        alt: 'Close-up of two warthogs grazing, showing their tusks and rough coats.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/warthogs-sidewalk-image.jpeg',
        alt: 'Two warthogs walking side by side across dry grassland with a lake in the distance.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/gorilla-family-image.jpeg',
        alt: 'A large silverback gorilla sitting beside a younger gorilla in dense green forest vegetation.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/rhino-grassland-image.jpeg',
        alt: 'A rhinoceros partially hidden in tall dry grass with scattered trees in the savanna.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/zebra-mother-calf-image.jpeg',
        alt: 'A zebra with its young calf grazing beside a tree in golden grassland.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/giraffe-silhouette-image.jpeg',
        alt: 'A tall giraffe standing against a hazy sky, surrounded by sparse trees.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/baboons-roadside-image.jpeg',
        alt: 'A troop of baboons gathered on a dirt road, grooming and interacting with each other.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/zebra-closeup-image.jpeg',
        alt: 'Close-up view of a zebra\'s black-and-white striped pattern with its mane standing upright.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/gorillas-resting-image.jpeg',
        alt: 'Two gorillas lying down and resting amidst dense green vegetation.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/rhino-pair-image.jpeg',
        alt: 'Two rhinoceroses grazing among dry bushes and grass in the savanna.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/zebras-grazing-image.jpeg',
        alt: 'A zebra and its calf feeding near trees, with another zebra grazing in the background.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/gorilla-duo-image.jpeg',
        alt: 'Two gorillas sitting closely together in lush greenery, one facing the other thoughtfully.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/zebra-herd-image.jpeg',
        alt: 'A small group of zebras in tall grass, with a mother and calf standing side by side.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/hippos-riverbank-image.jpeg',
        alt: 'A group of hippos with only their heads visible above the water near tall riverbank grass.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/giraffe-sunset-image.jpeg',
        alt: 'A giraffe standing tall against a hazy sunset sky with surrounding trees and bushes.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/baboon-mother-infant-image.jpeg',
        alt: 'A baboon sitting on the ground holding an infant close to her chest.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/baboons-duo-image.jpeg',
        alt: 'Two baboons in the savanna, one facing forward and one with its back turned.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
      {
        src: '/images/wildlife/elephant-riverbank-image.jpeg',
        alt: 'An elephant seen from behind, feeding on thick greenery along the river\'s edge.',
        width: 1600,
        height: 1067,
        blurDataURL: '',
      },
    ],
  },
];
